## OpenMMTools Integration

This enables OPS to use any testsystem from openmmtools to be used as well as add ANY possible OpenMM setup, not just the ones that we provided before. The old OpenMMEngine has been rename intp `SimpleOpenMMEngine`

In [1]:
import openpathsampling as paths
import openmmtools as omt
import simtk.openmm as omm
import simtk.unit as u
import mdtraj as md

import openpathsampling.engines.openmm as eng

Create Alanine in Vacuum and run it using OPS.

In [2]:
testsystem = omt.testsystems.AlanineDipeptideVacuum()

Let's have a look at the content

In [3]:
#! skip
{ key: type(value) for key, value in testsystem.__dict__.items()}

{'_positions': simtk.unit.quantity.Quantity,
 '_system': simtk.openmm.openmm.System,
 '_topology': simtk.openmm.app.topology.Topology}

An `OpenMM` simulation in OPS needs 3 ingredients to function
1. A template snapshot (which contains topolgy and coordinates/velocities), 
2. an OpenMM system object, and 
3. an OpenMM integrator object.

In the following we will get these parts.

#### 1. The template

The information for the template is contained in the `_topology` and the `_positions` object.

In [4]:
template = eng.snapshot_from_testsystem(testsystem)

#### 2. The system

This is easy since we directly get it from the testsytem objects

In [5]:
system = testsystem.system

#### 3. The integrator

The openmmtools system is (almost) independent of the integrator and `openmm` provides us with lots of options. For now we pick something simple.

In [6]:
integrator = omm.VerletIntegrator(
    0.002 * u.picoseconds    
)

build the engine

In [7]:
engine = eng.Engine(
    template.topology, 
    system, 
    integrator)

Let's run a simulation of 10 steps.

In [8]:
traj = engine.generate(template, [paths.LengthEnsemble(10).can_append])

In [9]:
print traj

Trajectory[10]


In [10]:
#! skip
print traj[5].coordinates

[[ 0.18766718  0.1159968   0.01245001]
 [ 0.19458355  0.22444931  0.00401419]
 [ 0.14436734  0.27122673  0.08869708]
 [ 0.14886755  0.25747469 -0.0892616 ]
 [ 0.33994538  0.26638275  0.00609838]
 [ 0.4270958   0.1897011   0.04380054]
 [ 0.36886501  0.38998327 -0.03181569]
 [ 0.293367    0.45243084 -0.05633822]
 [ 0.49859309  0.45657608 -0.02400118]
 [ 0.55814391  0.41515252  0.05735499]
 [ 0.57325357  0.43391329 -0.15561186]
 [ 0.51911283  0.48312771 -0.23640622]
 [ 0.67427635  0.47320488 -0.14414108]
 [ 0.58423084  0.32728145 -0.17536472]
 [ 0.47495213  0.60669035 -0.00127665]
 [ 0.35958394  0.64924198  0.00474684]
 [ 0.58359265  0.68379176  0.00902625]
 [ 0.67474234  0.64066118  0.00332434]
 [ 0.57127416  0.82897246  0.01853089]
 [ 0.46718925  0.8609547   0.02347773]
 [ 0.62214273  0.86301559  0.1087221 ]
 [ 0.61715895  0.87434292 -0.06931628]] nm


In [11]:
psi = md.compute_psi(traj.to_mdtraj())

/Users/jan-hendrikprinz/anaconda/lib/python2.7/site-packages/mdtraj/utils/validation.py:116: TypeCastPerformanceWarning: Casting unitcell_vectors dtype=float64 to <type 'numpy.float32'> 
  TypeCastPerformanceWarning)


In [12]:
#! ignore
psi[1][3:8]

array([[ 3.10614586],
       [-3.09586358],
       [ 3.13675642],
       [ 3.12832737],
       [ 3.09317803]], dtype=float32)

In [13]:
st = paths.Storage('engine_store_test.nc', mode='w')

In [14]:
st.engines.save(engine);
st.tag['template'] = template

The engine is stored by using the XML serialization of OpenMM and put this into the storage.

In [15]:
#! skip
st.variables['engines_json'][0][0:256] + '...'

u'{"_cls":"OpenMMEngine","_dict":{"integrator_xml":"<?xml version=\\"1.0\\" ?>\\n<Integrator constraintTolerance=\\"1e-05\\" stepSize=\\".002\\" type=\\"VerletIntegrator\\" version=\\"1\\"\\/>\\n","system_xml":"<?xml version=\\"1.0\\" ?>\\n<System openmmVersion=\\"7.0\\" type...'

In [16]:
st.save(traj);

In [17]:
st.close()

### try to load the stored engine

In [18]:
st = paths.AnalysisStorage('engine_store_test.nc')

In [19]:
engine = st.engines[0]

Run another 10 steps to test

In [20]:
template = st.tag['template']

In [21]:
traj = engine.generate(template, [paths.LengthEnsemble(10).can_append])

In [22]:
print traj

Trajectory[10]


In [23]:
st.close()

And save the trajectory for future use (other tests)

In [24]:
st = paths.Storage('engine_store_test.nc', "a")
st.save(traj)
st.close()